name: Router 自动签到

on:
  # 定时执行 - 每6小时执行一次
  schedule:
    - cron: '0 */6 * * *'

  # 手动触发
  workflow_dispatch:
    inputs:
      manual_run:
        description: '手动触发签到'
        required: false
        default: 'true'

jobs:
  checkin:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 安装 Playwright 浏览器
        run: |
          playwright install chromium
          playwright install-deps chromium

      - name: 执行签到
        env:
          ANYROUTER_ACCOUNTS: ${{ secrets.ANYROUTER_ACCOUNTS }}
          AGENTROUTER_ACCOUNTS: ${{ secrets.AGENTROUTER_ACCOUNTS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          CUSTOM_SMTP_SERVER: ${{ secrets.CUSTOM_SMTP_SERVER }}
          DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        run: |
          python main.py

      - name: 上传余额记录
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: balance-hash-${{ github.run_number }}
          path: balance_hash.txt
          retention-days: 7
